version: '3.9'

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: bloodbridge-db
    restart: always
    environment:
      POSTGRES_DB: bloodbridge
      POSTGRES_USER: bloodbridge_user
      POSTGRES_PASSWORD: bloodbridge_pass
    ports:
      - "5433:5432"
    volumes:
      - bloodbridge_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: bloodbridge-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  bloodbridge_data:
