import sys
from logging.config import fileConfig
from pathlib import Path

from alembic import context
from sqlalchemy import engine_from_config, pool

# Make `src` importable when alembic runs from the project root.
sys.path.append(str(Path(__file__).resolve().parents[1]))

from src.utils.database import Base, ensure_postgis  # noqa: E402
from src.utils.settings import settings  # noqa: E402

# Import every model module so Base.metadata is fully populated for autogenerate.
from src.donors import models as _donors_models  # noqa: F401,E402
from src.requestors import models as _requestors_models  # noqa: F401,E402
from src.hospitals import models as _hospitals_models  # noqa: F401,E402
from src.organizations import models as _organizations_models  # noqa: F401,E402
from src.blood_requests import models as _blood_requests_models  # noqa: F401,E402
from src.request_matches import models as _request_matches_models  # noqa: F401,E402
from src.chat import models as _chat_models  # noqa: F401,E402

config = context.config
config.set_main_option("sqlalchemy.url", settings.DATABASE_URL)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# geoalchemy2 ships its own Alembic integration: `include_object` skips
# PostGIS's internal bookkeeping tables (e.g. spatial_ref_sys), and
# `writer` fixes up autogenerated column defs so `import geoalchemy2`
# is actually included in the generated migration file.
from geoalchemy2.alembic_helpers import include_object, render_item, writer  # noqa: E402


def run_migrations_offline() -> None:
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
        render_item=render_item,
        process_revision_directives=writer,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    # PostGIS must exist before Alembic tries to create geography columns.
    ensure_postgis()

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            render_item=render_item,
            process_revision_directives=writer,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
