"""Add location to donors

Revision ID: 1b657d8f18b8
Revises: 4a9d7e1b2f3c
Create Date: 2026-09-26 11:35:32.762424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '1b657d8f18b8'
down_revision: Union[str, Sequence[str], None] = '4a9d7e1b2f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_geospatial_column('blood_requests', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.create_geospatial_index('idx_blood_requests_location', 'blood_requests', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_geospatial_column('donors', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True))
    op.create_geospatial_index('idx_donors_location', 'donors', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_geospatial_column('hospitals', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.create_geospatial_index('idx_hospitals_location', 'hospitals', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.add_geospatial_column('organizations', sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False))
    op.create_geospatial_index('idx_organizations_location', 'organizations', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_geospatial_index('idx_organizations_location', table_name='organizations', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('organizations', 'location')
    op.drop_geospatial_index('idx_hospitals_location', table_name='hospitals', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('hospitals', 'location')
    op.drop_geospatial_index('idx_donors_location', table_name='donors', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('donors', 'location')
    op.drop_geospatial_index('idx_blood_requests_location', table_name='blood_requests', postgresql_using='gist', column_name='location')
    op.drop_geospatial_column('blood_requests', 'location')
    # ### end Alembic commands ###
