"""initial schema

Revision ID: 22db9659d0b8
Revises: 
Create Date: 2026-08-20 02:12:59.902075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geography

# revision identifiers, used by Alembic.
revision: str = '22db9659d0b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('donors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('blood_type', sa.Enum('O_POS', 'O_NEG', 'A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', name='blood_type'), nullable=False),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('area_label', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_donors_location', 'donors', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_donors_email'), 'donors', ['email'], unique=True)
    op.create_geospatial_table('hospitals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_hospitals_location', 'hospitals', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_hospitals_email'), 'hospitals', ['email'], unique=True)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=True)
    op.create_geospatial_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('approval_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status_org'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_organizations_location', 'organizations', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_organizations_email'), 'organizations', ['email'], unique=True)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('requestors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('profile_pic_url', sa.String(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requestors_email'), 'requestors', ['email'], unique=True)
    op.create_geospatial_table('blood_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requestor_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('patient_name', sa.String(), nullable=False),
    sa.Column('blood_type_needed', sa.Enum('O_POS', 'O_NEG', 'A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', name='blood_type_needed'), nullable=False),
    sa.Column('units_needed', sa.Integer(), nullable=False),
    sa.Column('units_secured', sa.Integer(), nullable=False),
    sa.Column('urgency_level', sa.Enum('CRITICAL', 'URGENT', 'ROUTINE', name='urgency_level'), nullable=False),
    sa.Column('required_by', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hospital_name_text', sa.String(), nullable=True),
    sa.Column('hospital_id', sa.UUID(), nullable=True),
    sa.Column('is_hospital_backed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_VERIFICATION', 'ACTIVE', 'PARTIALLY_MATCHED', 'FULLY_MATCHED', 'FULFILLED', 'CLOSED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='request_status'), nullable=False),
    sa.Column('current_radius_km', sa.Float(), nullable=False),
    sa.Column('contact_phone', sa.String(), nullable=False),
    sa.Column('location', Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('area_label', sa.String(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requestor_id'], ['requestors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_blood_requests_location', 'blood_requests', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_table('request_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blood_request_id', sa.UUID(), nullable=False),
    sa.Column('donor_id', sa.UUID(), nullable=True),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('units_committed', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('ACCEPTED', 'CANCELLED', 'COMPLETED', name='match_status'), nullable=False),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blood_request_id'], ['blood_requests.id'], ),
    sa.ForeignKeyConstraint(['donor_id'], ['donors.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('request_match_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['request_match_id'], ['request_matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_match_id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_thread_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.Enum('DONOR', 'REQUESTOR', 'ORGANIZATION', name='sender_type'), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['chat_thread_id'], ['chat_threads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.drop_table('chat_threads')
    op.drop_table('request_matches')
    op.drop_geospatial_index('idx_blood_requests_location', table_name='blood_requests', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('blood_requests')
    op.drop_index(op.f('ix_requestors_email'), table_name='requestors')
    op.drop_table('requestors')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_email'), table_name='organizations')
    op.drop_geospatial_index('idx_organizations_location', table_name='organizations', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('organizations')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_email'), table_name='hospitals')
    op.drop_geospatial_index('idx_hospitals_location', table_name='hospitals', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('hospitals')
    op.drop_index(op.f('ix_donors_email'), table_name='donors')
    op.drop_geospatial_index('idx_donors_location', table_name='donors', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('donors')
    # ### end Alembic commands ###
