"""Drop requestors and fix inventories

Revision ID: 3f3f2c0e836f
Revises: 758a6edd9534
Create Date: 2026-09-22 00:37:14.634803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f3f2c0e836f'
down_revision: Union[str, Sequence[str], None] = '758a6edd9534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requestors_email'), table_name='requestors')
    op.drop_table('requestors')
    op.alter_column('blood_inventories', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_blood_inventories_blood_group_component_type'), table_name='blood_inventories')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_blood_inventories_blood_group_component_type'), 'blood_inventories', ['organization_id', 'blood_group', 'component_type'], unique=False)
    op.alter_column('blood_inventories', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('requestors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('profile_pic_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('password_changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('requestors_pkey'))
    )
    op.create_index(op.f('ix_requestors_email'), 'requestors', ['email'], unique=True)
    # ### end Alembic commands ###
