"""Merge requestor into donor

Revision ID: 758a6edd9534
Revises: ff01a1b2c3d4
Create Date: 2026-09-21 22:41:32.499494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
"""Merge requestor into donor

Revision ID: 758a6edd9534
Revises: ff01a1b2c3d4
Create Date: 2026-09-21 22:41:32.499494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '758a6edd9534'
down_revision: Union[str, Sequence[str], None] = 'ff01a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('blood_requests', sa.Column('donor_id', sa.UUID(), nullable=True))
    op.drop_index(op.f('ix_blood_requests_requestor_id'), table_name='blood_requests')
    op.create_index('ix_blood_requests_donor_id', 'blood_requests', ['donor_id'], unique=False)
    op.drop_constraint(op.f('blood_requests_requestor_id_fkey'), 'blood_requests', type_='foreignkey')
    op.create_foreign_key(None, 'blood_requests', 'donors', ['donor_id'], ['id'])
    op.drop_column('blood_requests', 'requestor_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_requests', sa.Column('requestor_id', sa.UUID(), autoincrement=False, nullable=True))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'blood_requests', type_='foreignkey')
    op.create_foreign_key(op.f('blood_requests_requestor_id_fkey'), 'blood_requests', 'requestors', ['requestor_id'], ['id'])
    op.drop_index('ix_blood_requests_donor_id', table_name='blood_requests')
    op.create_index(op.f('ix_blood_requests_requestor_id'), 'blood_requests', ['requestor_id'], unique=False)
    op.drop_column('blood_requests', 'donor_id')
    op.create_index(op.f('ix_blood_inventories_blood_group_component_type'), 'blood_inventories', ['organization_id', 'blood_group', 'component_type'], unique=False)
    op.alter_column('blood_inventories', 'last_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_table('safety_flags',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reporter_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reported_user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('excerpt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'open'::character varying"), autoincrement=False, nullable=False),
    sa.Column('resolution_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['blood_requests.id'], name=op.f('safety_flags_request_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('safety_flags_pkey'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('actor_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('actor_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('target_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_events_pkey'))
    )
    # ### end Alembic commands ###

