import type {
  AuditEvent,
  BloodRequest,
  Institution,
  SafetyFlag,
  User,
} from "../types";

export const seedUsers: User[] = [
  {
    id: "usr-admin",
    name: "Sara Khan",
    role: "Admin",
    phone: "+92 300 555 0101",
    email: "sara@hemalink.org",
    password: "Admin@123",
    isActive: true,
    createdAt: "2026-08-01",
  },
  {
    id: "usr-hospital",
    name: "Dr. Hamza Ali",
    role: "Hospital",
    phone: "+92 321 555 0144",
    email: "hamza@centralcityhospital.org",
    password: "Hospital@123",
    institutionId: "inst-central",
    isActive: true,
    createdAt: "2026-08-03",
  },
  {
    id: "usr-partner",
    name: "Ayesha Malik",
    role: "Partner",
    phone: "+92 333 555 0192",
    email: "ayesha@alkhidmat.org",
    password: "Partner@123",
    institutionId: "inst-alkhidmat",
    isActive: true,
    createdAt: "2026-08-05",
  },
  {
    id: "usr-requester",
    name: "Mariam Raza",
    role: "Donor",
    phone: "+92 312 555 0219",
    email: "mariam@example.org",
    password: "Donor@123",
    isActive: true,
    createdAt: "2026-08-10",
  },
];
export const seedInstitutions: Institution[] = [
  {
    id: "inst-central",
    name: "Central City Hospital",
    type: "Hospital",
    address: "Gulshan-e-Iqbal, Karachi",
    phone: "+92 21 3456 7000",
    contactName: "Dr. Hamza Ali",
    registrationStatus: "Approved",
    createdAt: "2026-08-03",
  },
  {
    id: "inst-jinnah",
    name: "Jinnah Medical Centre",
    type: "Hospital",
    address: "Nazimabad, Karachi",
    phone: "+92 21 3672 1000",
    contactName: "Dr. Nadia Ahmed",
    registrationStatus: "Pending",
    createdAt: "2026-08-18",
  },
  {
    id: "inst-alkhidmat",
    name: "Alkhidmat Welfare Centre",
    type: "Partner",
    address: "North Karachi, Karachi",
    phone: "+92 21 3690 2200",
    contactName: "Ayesha Malik",
    registrationStatus: "Approved",
    serviceArea: "Karachi Central",
    createdAt: "2026-08-05",
  },
  {
    id: "inst-edhi",
    name: "Edhi Blood Bank",
    type: "Partner",
    address: "Saddar, Karachi",
    phone: "+92 21 3241 3267",
    contactName: "Bilal Ahmed",
    registrationStatus: "Pending",
    serviceArea: "Karachi South",
    createdAt: "2026-08-20",
  },
];
export const seedRequests: BloodRequest[] = [
  {
    id: "req-1001",
    requesterId: "usr-requester",
    hospitalId: "inst-central",
    hospitalName: "Central City Hospital",
    isHospitalRegistered: true,
    bloodGroup: "O-",
    unitsRequired: 3,
    unitsFulfilled: 0,
    unitsRemaining: 3,
    urgency: "Urgent",
    requiredBy: "2026-08-27T18:00:00Z",
    status: "Pending hospital verification",
    trustLabel: "Self-verified",
    shortNote: "Emergency surgery scheduled for tomorrow.",
    distanceKm: 4.2,
    createdAt: "2026-08-26T08:40:00Z",
  },
  {
    id: "req-1002",
    requesterId: "usr-requester",
    hospitalId: "inst-central",
    hospitalName: "Central City Hospital",
    isHospitalRegistered: true,
    bloodGroup: "A+",
    unitsRequired: 2,
    unitsFulfilled: 0,
    unitsRemaining: 2,
    urgency: "Today",
    requiredBy: "2026-08-26T23:00:00Z",
    status: "Active",
    trustLabel: "Institution-backed",
    shortNote: "Required for a scheduled transfusion.",
    distanceKm: 7.1,
    createdAt: "2026-08-25T14:15:00Z",
  },
  {
    id: "req-1003",
    requesterId: "usr-requester",
    hospitalId: "inst-jinnah",
    hospitalName: "Jinnah Medical Centre",
    isHospitalRegistered: true,
    bloodGroup: "B+",
    unitsRequired: 4,
    unitsFulfilled: 2,
    unitsRemaining: 2,
    urgency: "Urgent",
    requiredBy: "2026-08-27T10:00:00Z",
    status: "Matched / In progress",
    trustLabel: "Partner fulfillment",
    shortNote: "Two units claimed by Alkhidmat Welfare Centre.",
    distanceKm: 9.8,
    createdAt: "2026-08-24T11:30:00Z",
  },
  {
    id: "req-1004",
    requesterId: "usr-requester",
    hospitalId: "inst-central",
    hospitalName: "Central City Hospital",
    isHospitalRegistered: true,
    bloodGroup: "AB+",
    unitsRequired: 1,
    unitsFulfilled: 1,
    unitsRemaining: 0,
    urgency: "Routine",
    requiredBy: "2026-08-24T12:00:00Z",
    status: "Fulfilled",
    trustLabel: "Partner fulfillment",
    fulfilledByInstitutionId: "inst-alkhidmat",
    createdAt: "2026-08-22T09:00:00Z",
  },
];
export const seedSafetyFlags: SafetyFlag[] = [
  {
    id: "flag-01",
    reporterId: "usr-requester",
    reportedUserId: "usr-partner",
    requestId: "req-1003",
    category: "Chat",
    excerpt:
      "User requested contact outside the platform before confirming willingness.",
    status: "Open",
    createdAt: "2026-08-26T09:20:00Z",
  },
  {
    id: "flag-02",
    reporterId: "usr-hospital",
    reportedUserId: "usr-requester",
    requestId: "req-1001",
    category: "Request",
    excerpt: "Request details may not match the hospital intake record.",
    status: "Open",
    createdAt: "2026-08-25T16:45:00Z",
  },
  {
    id: "flag-03",
    reporterId: "usr-partner",
    reportedUserId: "usr-requester",
    category: "User",
    excerpt: "Repeated cancellations after a match was accepted.",
    status: "Resolved",
    createdAt: "2026-08-21T12:10:00Z",
    resolutionNote: "Reviewed and dismissed after hospital confirmation.",
  },
];
export const seedAuditEvents: AuditEvent[] = [
  {
    id: "audit-01",
    actorId: "usr-admin",
    actorName: "Sara Khan",
    action: "Approved institution",
    targetType: "Institution",
    targetId: "inst-alkhidmat",
    timestamp: "2026-08-26T09:05:00Z",
  },
  {
    id: "audit-02",
    actorId: "usr-partner",
    actorName: "Ayesha Malik",
    action: "Claimed 2 units",
    targetType: "Request",
    targetId: "req-1003",
    timestamp: "2026-08-26T08:30:00Z",
  },
  {
    id: "audit-03",
    actorId: "usr-admin",
    actorName: "Sara Khan",
    action: "Resolved safety flag",
    targetType: "Safety flag",
    targetId: "flag-03",
    timestamp: "2026-08-25T15:20:00Z",
  },
];
